-- Supabase 排行榜建表 + 行级安全策略
-- 在 Supabase 控制台 → SQL Editor 里整段执行一次即可。

create table if not exists public.scores (
  id bigint generated by default as identity primary key,
  name text not null,
  score integer not null default 0,
  created_at timestamptz not null default now()
);

alter table public.scores enable row level security;

drop policy if exists "public read" on public.scores;
create policy "public read" on public.scores
  for select using (true);

drop policy if exists "public insert" on public.scores;
create policy "public insert" on public.scores
  for insert with check (true);
