-- Supabase 排行榜建表 + 行级安全策略
-- 在 Supabase 控制台 → SQL Editor 里整段执行一次即可。

create table if not exists public.scores (
  id bigint generated by default as identity primary key,
  name text not null,
  score integer not null default 0,
  created_at timestamptz not null default now()
);

alter table public.scores enable row level security;

drop policy if exists "public read" on public.scores;
create policy "public read" on public.scores
  for select using (true);

drop policy if exists "public insert" on public.scores;
create policy "public insert" on public.scores
  for insert with check (true);

-- ---------- 意见反馈 ----------
-- 公开可写入（网页端右下角“意见反馈”）；读取仅限服务端 / 控制台，避免内容被匿名拉取。
create table if not exists public.feedback (
  id bigint generated by default as identity primary key,
  content text not null check (char_length(content) between 1 and 2000),
  contact text,
  page text,
  user_agent text,
  ip text,
  created_at timestamptz not null default now()
);

alter table public.feedback enable row level security;

drop policy if exists "feedback public insert" on public.feedback;
create policy "feedback public insert" on public.feedback
  for insert with check (true);

-- ---------- 在线访客统计 ----------
-- 以 IP 为主键去重；页面打开时插入（冲突则忽略，保留 first_seen），
-- 之后每 60s 心跳更新 last_seen。在线数 = last_seen 在 2 分钟内的行数：
--   select count(*) from public.visitors where last_seen > now() - interval '2 minutes';
create table if not exists public.visitors (
  ip text primary key,
  user_agent text,
  page text,
  first_seen timestamptz not null default now(),
  last_seen timestamptz not null default now()
);

alter table public.visitors enable row level security;

drop policy if exists "visitors public read" on public.visitors;
create policy "visitors public read" on public.visitors
  for select using (true);

drop policy if exists "visitors public insert" on public.visitors;
create policy "visitors public insert" on public.visitors
  for insert with check (true);

drop policy if exists "visitors public update" on public.visitors;
create policy "visitors public update" on public.visitors
  for update using (true) with check (true);
