// 英语「流利说·刷句子」内容：小学到高中 12 个年级 + 随机混合
// 每项：[英文句子, 中文翻译]

export const ENGLISH_GRADES = [
  { id: 'p1', name: '一年级', group: '小学' },
  { id: 'p2', name: '二年级', group: '小学' },
  { id: 'p3', name: '三年级', group: '小学' },
  { id: 'p4', name: '四年级', group: '小学' },
  { id: 'p5', name: '五年级', group: '小学' },
  { id: 'p6', name: '六年级', group: '小学' },
  { id: 'j1', name: '初一', group: '初中' },
  { id: 'j2', name: '初二', group: '初中' },
  { id: 'j3', name: '初三', group: '初中' },
  { id: 's1', name: '高一', group: '高中' },
  { id: 's2', name: '高二', group: '高中' },
  { id: 's3', name: '高三', group: '高中' },
  { id: 'random', name: '随机混合', group: '混合' },
];

export const ENGLISH_DECK = {
  p1: [
    ['Hello!', '你好！'],
    ['Good morning.', '早上好。'],
    ['Good afternoon.', '下午好。'],
    ['I am a boy.', '我是男孩。'],
    ['I am a girl.', '我是女孩。'],
    ['This is a cat.', '这是一只猫。'],
    ['This is a dog.', '这是一只狗。'],
    ['I like red.', '我喜欢红色。'],
    ['I like apples.', '我喜欢苹果。'],
    ['What is your name?', '你叫什么名字？'],
    ['My name is Amy.', '我叫艾米。'],
    ['Thank you.', '谢谢你。'],
  ],
  p2: [
    ['She is my sister.', '她是我妹妹。'],
    ['He is my brother.', '他是我哥哥。'],
    ['This is my mother.', '这是我妈妈。'],
    ['This is my father.', '这是我爸爸。'],
    ['The sky is blue.', '天空是蓝色的。'],
    ['I can swim.', '我会游泳。'],
    ['I can run fast.', '我跑得快。'],
    ['We are friends.', '我们是朋友。'],
    ['I have a new book.', '我有一本新书。'],
    ['Where is my bag?', '我的书包在哪里？'],
    ['I go to school.', '我去上学。'],
    ['I am seven years old.', '我七岁了。'],
  ],
  p3: [
    ['I like to read books.', '我喜欢读书。'],
    ['I have a pet dog.', '我有一只宠物狗。'],
    ['She can sing very well.', '她唱歌很好。'],
    ['It is sunny today.', '今天阳光明媚。'],
    ['I eat breakfast every day.', '我每天吃早饭。'],
    ['The apple is red and sweet.', '苹果又红又甜。'],
    ['My school is big and clean.', '我的学校又大又干净。'],
    ['I play football after school.', '我放学后踢足球。'],
    ['Can you help me?', '你能帮我吗？'],
    ['I go to bed at nine.', '我九点睡觉。'],
    ['There are many books on the desk.', '桌子上有很多书。'],
    ['I want to be a teacher.', '我想当老师。'],
  ],
  p4: [
    ['I get up at seven o\'clock.', '我七点起床。'],
    ['My favorite subject is English.', '我最喜欢的科目是英语。'],
    ['She is good at drawing.', '她擅长画画。'],
    ['We have lunch at school.', '我们在学校吃午饭。'],
    ['The weather is fine today.', '今天天气很好。'],
    ['I like playing the piano.', '我喜欢弹钢琴。'],
    ['There is a garden behind my house.', '我家后面有个花园。'],
    ['He usually goes to work by bike.', '他通常骑自行车上班。'],
    ['I want to visit the Great Wall.', '我想去参观长城。'],
    ['The library is near the playground.', '图书馆在操场附近。'],
    ['I did my homework last night.', '我昨晚做了作业。'],
    ['She is taller than me.', '她比我高。'],
  ],
  p5: [
    ['I am interested in science.', '我对科学感兴趣。'],
    ['We should protect the environment.', '我们应该保护环境。'],
    ['He often helps his mother do housework.', '他经常帮妈妈做家务。'],
    ['The Spring Festival is my favorite holiday.', '春节是我最喜欢的节日。'],
    ['I have been to Beijing twice.', '我去过北京两次。'],
    ['Reading is good for us.', '读书对我们有好处。'],
    ['She practices the piano every evening.', '她每晚练钢琴。'],
    ['My dream is to be a doctor.', '我的梦想是当医生。'],
    ['There are many animals in the zoo.', '动物园里有很多动物。'],
    ['We went to the park last Sunday.', '上周日我们去了公园。'],
    ['It is important to exercise every day.', '每天锻炼很重要。'],
    ['The book is more interesting than that one.', '这本书比那本更有趣。'],
  ],
  p6: [
    ['I will graduate from primary school this year.', '我今年就要小学毕业了。'],
    ['My parents are proud of me.', '我的父母为我感到骄傲。'],
    ['We should study hard for our future.', '我们应该为未来努力学习。'],
    ['He is one of the best students in our class.', '他是我们班最好的学生之一。'],
    ['I am looking forward to the summer holiday.', '我期待暑假。'],
    ['The environment is becoming better and better.', '环境正在变得越来越好。'],
    ['She has learned English for three years.', '她学英语三年了。'],
    ['It takes me twenty minutes to walk to school.', '我走路到学校要二十分钟。'],
    ['We had a wonderful time at the party.', '我们在聚会上玩得很开心。'],
    ['I want to make more friends in middle school.', '我想在初中交更多朋友。'],
    ['He is not only clever but also hardworking.', '他不仅聪明而且努力。'],
    ['Thank you for helping me all these years.', '感谢这些年来你对我的帮助。'],
  ],
  j1: [
    ['My new school is very beautiful.', '我的新学校很漂亮。'],
    ['I get up early every morning.', '我每天早上起得很早。'],
    ['English is my favorite subject.', '英语是我最喜欢的科目。'],
    ['There are forty students in our class.', '我们班有四十名学生。'],
    ['I often play basketball with my classmates.', '我经常和同学打篮球。'],
    ['She usually goes to school by subway.', '她通常坐地铁上学。'],
    ['I want to learn more about Chinese history.', '我想多了解中国历史。'],
    ['Reading English every day is important.', '每天读英语很重要。'],
    ['My mother asks me to do my homework first.', '妈妈让我先做作业。'],
    ['We had a picnic in the park last weekend.', '上周末我们在公园野餐。'],
    ['He is good at math and physics.', '他擅长数学和物理。'],
    ['I believe I can do it well.', '我相信我能做好。'],
  ],
  j2: [
    ['I will go to the movies with my friends tonight.', '今晚我要和朋友去看电影。'],
    ['He has been learning to swim for two years.', '他学游泳两年了。'],
    ['We should help each other and learn from each other.', '我们应该互相帮助、互相学习。'],
    ['The more you read, the more you will know.', '你读得越多，知道得越多。'],
    ['She spent the whole afternoon reading novels.', '她整个下午都在读小说。'],
    ['It is necessary for us to protect wild animals.', '保护野生动物对我们很必要。'],
    ['I am going to visit my grandparents this weekend.', '这周末我要去看望祖父母。'],
    ['The weather will be sunny tomorrow.', '明天天气会晴朗。'],
    ['He made great progress in his English study.', '他的英语学习进步很大。'],
    ['We plan to take part in the school sports meeting.', '我们计划参加校运动会。'],
    ['It is dangerous to play with fire.', '玩火很危险。'],
    ['I wonder how far it is from here to the station.', '我想知道从这里到车站有多远。'],
  ],
  j3: [
    ['I am busy preparing for the entrance exam.', '我正忙着准备升学考试。'],
    ['We should make full use of our time.', '我们应该充分利用时间。'],
    ['She has made up her mind to study abroad.', '她下定决心出国留学。'],
    ['The harder you work, the better results you will get.', '你越努力，成绩越好。'],
    ['I am grateful to my teachers for their help.', '我感谢老师们的帮助。'],
    ['He succeeded in passing the final exam.', '他成功通过了期末考试。'],
    ['We will never forget our happy school days.', '我们永远不会忘记快乐的学生时代。'],
    ['It is important to keep a balance between study and rest.', '保持学习与休息的平衡很重要。'],
    ['I look forward to entering a good high school.', '我期待进入一所好高中。'],
    ['She encourages me to face difficulties bravely.', '她鼓励我勇敢面对困难。'],
    ['Knowledge can change our life.', '知识能改变我们的生活。'],
    ['We should never give up our dreams.', '我们永远不要放弃梦想。'],
  ],
  s1: [
    ['High school life is both challenging and colorful.', '高中生活既充满挑战又丰富多彩。'],
    ['I have decided to join the English club.', '我决定加入英语社团。'],
    ['We should develop good learning habits.', '我们应该养成好的学习习惯。'],
    ['The Internet has changed the way we communicate.', '互联网改变了我们的交流方式。'],
    ['It is said that practice makes perfect.', '俗话说熟能生巧。'],
    ['She is interested in science and technology.', '她对科学技术感兴趣。'],
    ['We must take measures to protect the environment.', '我们必须采取措施保护环境。'],
    ['I find it necessary to improve my spoken English.', '我发现提高英语口语很有必要。'],
    ['The library is a good place to study.', '图书馆是学习的好地方。'],
    ['He advised me to read more English newspapers.', '他建议我多读英文报纸。'],
    ['Success belongs to those who work hard.', '成功属于努力的人。'],
    ['I am looking forward to the coming winter vacation.', '我期待即将到来的寒假。'],
  ],
  s2: [
    ['We are faced with more pressure in our study.', '我们的学习压力更大了。'],
    ['She is determined to be admitted to a key university.', '她决心考上一所重点大学。'],
    ['The lecture given by the professor was very inspiring.', '教授的讲座非常鼓舞人心。'],
    ['We should attach importance to our physical health.', '我们应该重视身体健康。'],
    ['It is well known that English is widely used in the world.', '众所周知，英语在世界各地被广泛使用。'],
    ['He devoted all his time to scientific research.', '他把全部时间都投入到科学研究中。'],
    ['The government has taken action to reduce air pollution.', '政府已采取行动减少空气污染。'],
    ['I am convinced that hard work will pay off.', '我坚信努力会有回报。'],
    ['We should learn to manage our time wisely.', '我们应该学会明智地管理时间。'],
    ['The problem is more difficult than we expected.', '这个问题比我们预想的更难。'],
    ['Reading widely can broaden our horizons.', '广泛阅读能开阔我们的视野。'],
    ['She not only sings well but also dances beautifully.', '她不仅唱得好，舞也跳得美。'],
  ],
  s3: [
    ['I am preparing for the college entrance examination.', '我正在为高考做准备。'],
    ['We should stay calm and confident before the exam.', '考前我们要保持冷静和自信。'],
    ['It is essential to review what we have learned.', '复习所学知识至关重要。'],
    ['She has made great efforts to achieve her dream.', '她为实现梦想付出了巨大努力。'],
    ['The more knowledge we have, the more competitive we will be.', '知识越多，我们越有竞争力。'],
    ['I believe that nothing is impossible to a willing heart.', '我相信有志者事竟成。'],
    ['We should make the most of every minute.', '我们应该充分利用每一分钟。'],
    ['He overcame many difficulties and finally succeeded.', '他克服了许多困难最终成功了。'],
    ['Perseverance is the key to success.', '坚持是成功的关键。'],
    ['I will always remember the encouragement from my teachers.', '我会永远记得老师的鼓励。'],
    ['We are about to graduate and start a new chapter of life.', '我们即将毕业，开启人生新篇章。'],
    ['Life is like a journey; we should enjoy every step.', '人生如旅程，我们应享受每一步。'],
  ],
};
